language: python
before_install:
- echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- mkdir -p ~/.ssh
- chmod 700 ~/.ssh
- openssl aes-256-cbc -K $encrypted_6b10a682c05b_key -iv $encrypted_6b10a682c05b_iv
  -in ot-ot-gh-pages.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- eval "$(ssh-agent -s)"
- ssh-add ~/.ssh/id_rsa
- git config --global user.email "<travis-ci@owntracks.org>"
- git config --global user.name "OwnTracks (via TravisCI)"
- git config --global push.default simple
python:
- '3.9'
install: pip install -r requirements.txt
script:
- git clone git@github.com:owntracks/owntracks.git
- cd owntracks
- git checkout gh-pages
- git pull
- ls -l booklet
- cd ..
- git clone https://github.com/owntracks/booklet.git
- cd booklet
- mkdocs build --clean
- ls -l _site
- cp -R _site/* ../owntracks/booklet/
- cd ../owntracks/booklet/
- git status
- git add .
- if [ -n "$(git status --porcelain)" ]; then  git commit -m 'TravisCI rebuild' -a;
  fi
- git push
